### ISSUE TITLE
Add reference of image to FileSystem.Mount() call.

### ISSUE THREAD

**Issue by siscia** [ktock/remote-snapshotter#7]
Hi all,at the moment the FileSystem mount interface take as input the reference of the image, the digest of the layer and the mountpoint.

```
type FileSystem interface {
	Mount(ctx context.Context, ref, digest, mountpoint string) error
	Check(ctx context.Context, mountpoint string) error
}
```

I have some doubts about the use of the reference of the image.

For us, cvmfs+unpacked, it would be much more beneficial to have the digest of the image, something like sha256:.... instead of the reference library/redis.

This would allow us to kind of cheat (like mount empty layer at the bottom and only the complete one at the top).
So I am wondering if it is possible to add the digest of the image, not of the layer, to the FileSystem.Mount() call.

We cannot rely just on the reference of the image, because the same image (hence an image with the same digest) can have different reference. 

Moreover, same reference does not guarantee that the image is identical.I didn't look too deep into the details of stargz and how this is managed though.
 
Let me know your thoughts!

Cheers,
Simone

**Comment by ktock** [comment]
@siscia Thank you for opening this issue! I agree that rootfs-driven filesystems require the digest of the image.

 I'm thinking to add the digest of the image's manifest to the API. [A manifest contains layer digests](https://docs.docker.com/registry/spec/manifest-v2-2/#example-image-manifest) so the manifest's digest corresponds to the image contents and can be used as an "image digest". 

```
type FileSystem interface {
	Mount(ctx context.Context, manifest, ref, digest, mountpoint string) error
	Check(ctx context.Context, mountpoint string) error
}
```
(Names are still needed for registry-backed filesystems because [registry API requires them](https://docs.docker.com/registry/spec/api/#pulling-a-layer).)

The PoC is on [this branch](https://github.com/ktock/remote-snapshotter/tree/passing-through-annotations). I'm currently working on [necessary patches on containerd](https://github.com/ktock/containerd/commit/54bdb68aa2cf9fd5cd0ad65232ecf33f808643ac) for propagating image-related information to remote snapshotter.

**Comment by siscia** [comment]
That would be wonderful!

Let me know if you need anything from my side!

**Comment by ktock** [comment]
Now we can do it with the new FileSystem interface introduced by #10 🎉
